---
- ansible.builtin.include_tasks: "./install_ansible_{{ ansible_facts.os_family | lower }}.yml"

- name: Install packages using PIP
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-lint
      - yamllint
    state: latest

- name: Add ansible plugin to .zshrc
  ansible.builtin.replace:
    dest: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: '^plugins=\(((?!.*\bansible\b).*)\)$'
    replace: 'plugins=(\1 ansible)'
