---
- name: Get VS Code signing key
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
    owner: root
    group: root
    mode: 0644

- name: Add VS Code Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
    state: present
    update_cache: true
    filename: vscode

- name: Install VS Code with APT
  become: true
  ansible.builtin.apt:
    name: code
    state: latest
