---
all:
  hosts:
    pc:
      ansible_host: 192.168.1.10
    dev-vm:
      ansible_host: 192.168.1.11
    laptop:
      ansible_host: 192.168.1.12
    server:
      ansible_host: 192.168.1.13
  children:
    docker:
      hosts:
        pc:
        dev-vm:
        laptop:
        server:
    virt:
      hosts:
        pc:
        laptop:
    dev:
      hosts:
        pc:
        laptop:
    dev_java:
      hosts:
        dev-vm:
    dev_python:
      hosts:
        dev-vm:
    dev_ansible:
      hosts:
    desktop:
      children:
        desktop_all:
          hosts:
            pc:
            laptop:
        desktop_dev:
          hosts:
            dev-vm:
        desktop_virt:
          hosts:
        desktop_pc:
          hosts:
        desktop_work:
          hosts:
            dev-vm:
        desktop_gaming:
          hosts:
