---
- ansible.builtin.include_tasks: "./install_virt_{{ ansible_facts.os_family | lower }}.yml"

- name: Add {{ ansible_facts.user_id }} to the libvirt group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    groups: libvirt
    append: true

- name: Ensure ~/.config/libvirt exists
  ansible.builtin.file:
    path: "~{{ ansible_facts.user_id }}/.config/libvirt"
    state: directory
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0755

- name: Make qemu://system the default connection
  ansible.builtin.copy:
    dest: "~{{ ansible_facts.user_id }}/.config/libvirt/libvirt.conf"
    content: >
      uri_default = "qemu:///system"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0644
