---
- name: Install flatpak packages
  become: true
  community.general.flatpak:
    name: '{{ flatpak_package }}'
  with_items: '{{ gaming_flatpak_apps }}'
  loop_control:
    loop_var: flatpak_package
