---
- name: Install flatpak using DNF
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: latest

- name: Install base packages using DNF
  become: true
  ansible.builtin.dnf:
    name: "{{ base_packages }}"
    state: latest
