---
- name: Install requirements using DNF
  become: true
  ansible.builtin.dnf:
    name:
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
    state: latest
