---
- name: Install prerequisites using DNF
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: latest

- name: Add GPG key
  become: true
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/fedora/gpg
    state: present

- name: Add Docker repository.
  become: true
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/fedora/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install base packages using DNF
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
