---
- name: Change shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    shell: /bin/zsh
  when: "'/bin/zsh' not in ansible_facts.user_shell"

- ansible.builtin.import_tasks: ./zsh_install_omz.yml
- ansible.builtin.import_tasks: ./zsh_configure.yml
