---
- name: Configure ohmyzsh theme
  ansible.builtin.lineinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: '^(#)?(\s)*ZSH_THEME='
    line: 'ZSH_THEME="{{ zsh_theme }}"'

- name: Configure ohmyzsh to be hyphen insensitive
  ansible.builtin.lineinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: '^(#)?(\s)*HYPHEN_INSENSITIVE='
    line: 'HYPHEN_INSENSITIVE="true"'

- name: Configure ohmyzsh to auto update
  ansible.builtin.lineinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: >
      ^(#)?(\s)*zstyle ':omz:update' mode auto.*
    line: "zstyle ':omz:update' mode auto"

- name: Configure ohmyzsh to auto update every 2 weeks
  ansible.builtin.lineinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: >
      ^(#)?(\s)*zstyle \':omz:update\' frequency.*
    line: "zstyle ':omz:update' frequency 14"

- name: Enable plugins
  ansible.builtin.replace:
    dest: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: '^plugins=\(((?!.*\bgit zsh-syntax-highlighting zsh-autocomplete\b).*)\)$'
    replace: 'plugins=(\1 git zsh-syntax-highlighting zsh-autocomplete)'

- name: Set editor to micro
  ansible.builtin.lineinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: '^(#)?(\s)*export EDITOR='
    line: "export EDITOR='micro'"

- name: Add ~/.local/bin to PATH
  ansible.builtin.lineinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    regexp: '^(#)?(\s)*export PATH='
    line: "export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH"

- name: Create .aliases file
  ansible.builtin.template:
    src: templates/aliases.j2
    dest: ~{{ ansible_facts.user_id }}/.aliases
    mode: 0600

- name: Setup aliases
  ansible.builtin.blockinfile:
    path: "~{{ ansible_facts.user_id }}/.zshrc"
    marker: "# {mark} source aliases from ~/.aliases"
    block: |
      source ~/.aliases
